// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddEvent'](arg1, arg2, arg3);
}

export function DeleteEvent(arg1) {
  return window['go']['main']['App']['DeleteEvent'](arg1);
}

export function GetEvents() {
  return window['go']['main']['App']['GetEvents']();
}
