// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddEvent(arg1:string,arg2:string,arg3:string):Promise<main.Event>;

export function DeleteEvent(arg1:string):Promise<void>;

export function GetEvents():Promise<Array<main.Event>>;
